<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="innovationteam-ThinkPad-T440p" name="zytest.custonboardapp.tests.TemplateUploadTest" tests="5" failures="0" timestamp="9 Nov 2018 14:27:23 GMT" time="7.972" errors="1">
  <testcase name="testGetTenantConfigResponse" time="2.676" classname="zytest.custonboardapp.tests.TemplateUploadTest"/>
  <testcase name="testGetTenantConfig" time="1.934" classname="zytest.custonboardapp.tests.TemplateUploadTest"/>
  <testcase name="testCreateCustomer" time="0.021" classname="zytest.custonboardapp.tests.TemplateUploadTest">
    <error type="java.lang.UnsupportedOperationException" message="JsonObject">
      <![CDATA[java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at zytest.custonboardapp.tests.TemplateUploadTest.testCreateCustomer(TemplateUploadTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </error>
  </testcase> <!-- testCreateCustomer -->
  <testcase name="testUploadXlsPositiveCase" time="1.539" classname="zytest.custonboardapp.tests.TemplateUploadTest"/>
  <testcase name="testUploadXlsErrorCase" time="1.802" classname="zytest.custonboardapp.tests.TemplateUploadTest"/>
</testsuite> <!-- zytest.custonboardapp.tests.TemplateUploadTest -->
